import fileops

files = ["testdir/test.txt.part0", "testdir/test.txt.part1"]

# fileops.open_exe("/Applications/Google Chrome.app/")
# fileops.close_exe("/Applications/Google Chrome.app/")
# fileops.create_file("./test.txt")
# print(fileops.write_file("./test.txt", "Hi Mom!"))
# print(fileops.read_file("./test.txt"))
# fileops.copy_file_to_clipboard("./test.txt")  #Hi Mom!
# fileops.append_data_to_file("./test.txt", " Hi Dad!")
# fileops.make_dir("./testdir")
# fileops.move_file("./test.txt", "testdir/test.txt")
# print(fileops.get_file_size("testdir/test.txt"))
# print(fileops.does_file_exist("testdir/test.txt"))
# print(fileops.list_dir_files("../"))
# print(fileops.get_file_perm("testdir/test.txt"))
# print(fileops.get_file_type("testdir/test.txt"))
# print(fileops.get_num_lines("testdir/test.txt"))
# print(fileops.get_num_words("testdir/test.txt"))
# print(fileops.get_word_freq("testdir/test.txt", "Hi"))
# print(fileops.get_num_chars("testdir/test.txt"))
# print(fileops.get_char_freq("testdir/test.txt", "H"))
# fileops.create_temp_file()
# print(fileops.is_dir_empty("./"))
# print(fileops.get_system_usage("./"))
# fileops.monitor_file("testdir/test.txt")
# print(fileops.get_base64("testdir/test.txt"))
# fileops.create_symbolic_link("testdir/test.txt", "testdir/test")
# fileops.split_file("testdir/test.txt", 2)
# fileops.merge_file(files, "testdir/testmerge.txt")
# fileops.replace_data("testdir/test.txt", "Hi Dad!", "Bye Dad!")
# fileops.monitor_dir("./")
# print(fileops.does_dir_exist("testdir"))
# print(fileops.does_data_exist("testdir/test.txt", "Hi Mom"))
# print(fileops.compare_files("testdir/test.txt", "testdir/test.txt.part0"))
# concat = ["testdir/test.txt.part0", "testdir/test.txt.part1"]
# fileops.concat_files(files, "testdir/testconcat.txt")
# print(get_data_from_file("testdir/test.txt", "Bye Mom"))
# fileops.delete_file("testdir/test.txt.part0")
# fileops.delete_dir("testdir/testdir2")
# fileops.change_file_perm("testdir/test.txt", 777)
